### ISSUE TITLE
Start dev. Track progress

### ISSUE THREAD

**Issue by abbadon1334** [atk4/outbox#1]
- [x] Models
- [x] Mailer
- [x] Implement Gmail as Mailer
- [x] Outbox must be used with and without App
- [ ] Queue Sending
- [x] send -> Single Response 
- [x] send -> Multiple Response ( some API return multiple response)
- [x] send -> Response -> Multiple email errors
- [ ] WebHooks - some API, give a partial OK response, for Validated Mail message, but after that call back a url with response of sending actions 

I see two ways of sending emails : 

```php

/** @var Outbox $outbox */
$outbox = $this->getApp()->getOutbox();

$mail = $outbox->new()
    ->withTemplateIdentifier('test')
    ->replaceContent('test','testing')
;

$outbox->send($mail);
```

```php
/** @var Outbox $outbox */
$outbox = $app->getOutbox();

$outbox->callableSend(static function(Mail $mail) use ($user_model) {

    $mail->withTemplateIdentifier('test')
        ->replaceContent('test','testing')
        ->replaceContent( $user_model, 'user');

    return $mail;
});
```

**Comment by georgehristov** [comment]
@abbadon1334 I cannot grasp your idea in entirety but I can throw a few ideas from the implementation I currently have (which I have to migrate to ATK):
- using [PHPMailer](https://github.com/PHPMailer/PHPMailer) as class to handle the actual mail sending
- using [php-imap](https://github.com/barbushin/php-imap) for reading emails to the system
- Model for e-mail accounts (system-wide and user specific) - User can send from one of his assigned accounts. System sends from the system assigned account
- Model for boilerplates (common and user-specific) - templates of messages (we can very well use ATK templating engine)
- Model for mail history - specific mails can be stored in the system for reference. They can appear related to various records in the system
- MailHandler class which controls the sending (and receiving/parsing) of emails, identifies relations to records (based on sender, subject, etc), and also defines the available boilerplate fields, default attachments, etc. MailHandler class is extended to adjust for different scenarios

**Comment by abbadon1334** [comment]
> @abbadon1334 I cannot grasp your idea in entirety but I can throw a few ideas from the implementation I currently have (which I have to migrate to ATK):
> 
>     * using [PHPMailer](https://github.com/PHPMailer/PHPMailer) as class to handle the actual mail sending
I think we need an interface to decouple PHPMailer or service API like sendinblue/sparkpost
> 
>     * using [php-imap](https://github.com/barbushin/php-imap) for reading emails to the system
I think this can be a good step later, to add some mail client functionalities or automations that activate actions by reading special tags/code in emails directly from imap inboxes
> 
>     * Model for e-mail accounts (system-wide and user specific) - User can send from one of his assigned accounts. System sends from the system assigned account
>     * Model for boilerplates (common and user-specific) - templates of messages (we can very well use ATK templating engine)
I think this two point can be generalized in a templating system, why use ATK template system.
IMHO to add a template management system with a WYSIWYG Editor is much easier with replacement tokens then a template system even if this is simple like the ATK Template
> 
>     * Model for mail history - specific mails can be stored in the system for reference. They can appear related to various records in the system
Yes but i don't think that this can be added directly or at least can be add as a trait or a addon/helper for model, but not as a core feature
>     * MailHandler class which controls the sending (and receiving/parsing) of emails, identifies relations to records (based on sender, subject, etc), and also defines the available boilerplate fields, default attachments, etc. MailHandler class is extended to adjust for different scenarios

My idea is to have a Outbox class that can be used with or without App, Outbox has a mailer system which send Emails, every Email can be replaced with a MailTemplate, Email can have some tokens that can be replaced, Email can be send.

Some API have webhooks which will be called back by the SMTP service on every defined actions, for that every email can have multiple response.
